.github/workflows/pr-lint.yml
Adds main as a valid scope for PRs. It is required to use release-please with PR per package.
=> feat: add main as a valid scope

.github/workflows/python-service.yml
- if feature:
- Overview of assigned task including architecture and code changes
- if fix:
- Explanation of the problems behavior & reproduction steps, the code culprit and the solution.
- if else:
- List of changes made and the reasons/benefits.
Use the module option for mypy instead of the package one and then explicitly treating modules as packages
=> feat: simplify mypy by using the module option

.github/workflows/python-service.yml
=> feat: run pytest with modules

.github/workflows/python-service.yml
- if feature:
- Overview of assigned task including architecture and code changes
- if fix:
- Explanation of the problems behavior & reproduction steps, the code culprit and the solution.
- if else:
- List of changes made and the reasons/benefits.
Extra information to contextualize the reviewer. Some images or diagrams are welcome.
Point to a file or code element that's the entry point for the current PR subject
=> feat: allow other branches to be deployed as main branch

.github/workflows/python-service.yml
Add support for SSH key so we can install git repos.
=> feat: add support for ssh key

.github/workflows/python-service.yml
=> feat: add coverage to tests run

.github/workflows/pr-lint.yml
He actualizado la version del action de la pr-lint a la última versión
=> fix: bump action semantic pull request v5.4.0

.github/workflows/release-please.yml
Centralizamos de esta manera la version de release please
=> feat: adds release-please workflow

.github/workflows/release-please.yml
- Se cambia el repo del release please.
=> feat: update release-please workflow

.github/workflows/app-android.yml, .github/workflows/app-ios.yml, .github/workflows/node-service-iam.yml, .github/workflows/node-service.yml, .github/workflows/python-service.yml, .github/workflows/web-deploy.yml
- Se corrige un error. Al cambiar prepare-matrix por prepare, no se cambiaron los fromJson needs.
=> fix: fix error with needs n prepare matrix

.github/workflows/python-service-ruff.yml
Deja de usar flake y black para usar ruff
Cuando se deje de usar el actual "python-service", renombraría este
=> feat: add Python service build and deploy workflow with ruff for monorepo CI

.github/workflows/python-library.yml
Sencilla y sin reportes de cobertura, que no les hacemos caso, podemos meterlo cuando lo veamos oportuno
=> feat: python library workflow (ruff, uv, tests)

.github/workflows/python-service-ruff-uv.yml
Probado aquí: https://github.com/taxdown/adri-latest/actions/runs/12416398051/job/34664942358
=> feat: python service workflow with ruff and uv

.github/workflows/python-service-ruff-uv.yml
- Change default main branch from 'master' to 'main'
- Add 'github-app-id' input for GitHub App token generation
- Replace GIT_TOKEN with GITHUB_APP_PRIVATE_KEY for authentication
- Ensure GIT_TOKEN is set before running Python dependency installation
- Update steps for installing NPM dependencies and configuring Git
=> fix: update GitHub Actions workflow for Python service

.github/workflows/python-service-ruff-uv.yml
=> fix: add GIT_TOKEN environment variable for deployment in GitHub Actions workflow (python-service-ruff-uv)

.github/workflows/python-service-ruff-uv.yml
- add npm_token to deployment step in python-service workflow
- install infrastructure dependencies in python-service workflow
=> feat: add npm_token to deployment step and install infrastructure dependencies in python-service workflow

.github/workflows/python-service-ruff-uv.yml
=> fix: add npm registry configuration step to python-service workflow

.github/workflows/python-service-ruff-uv.yml
- Consolidated build and test steps into a single 'build-and-test' job for clarity.
- Added 'deploy' job.
- Removed the 'run-coverage' input and integrated coverage checks directly into the testing process.
- Updated step names for better readability, including renaming 'Run python sanity checks for service' to 'Python code linting with Ruff'.
- Added step for running infrastructure tests.
- Improved environment variable handling by utilizing SERVICE_PATH for directory navigation.
- Streamlined deployment steps and ensured proper authentication with GIT_TOKEN and NODE_AUTH_TOKEN.
=> refactor: enhance GitHub Actions workflow for Python service

.github/workflows/release-please-app.yml
Update Worfklow v4 release-please-action
=> fix: update config release-please-v4

.github/workflows/python-service-ruff.yml, .github/workflows/python-service.yml
Me habia dejado cosas sin limpiar bien
=> chore: clean coverage options previously removed

.github/workflows/python-service-ruff.yml, .github/workflows/python-service.yml
Poetry 2 introduce breaking changes asi que hay que fijarla a la ultima de la 1. Con suerte iremos quitando las dependencias de poetry.
=> chore: fix poetry version to 1.8.5

.github/workflows/web-deploy.yml
Mejora la seguridad y configuración del despliegue web mediante la implementación de roles IAM y permisos OIDC
- Añade permisos específicos para `id-token` y `contents` en la configuración del despliegue web
=> ci: add permissions for id-token and contents in web-deploy configuration

.github/actions/setup-github-ssh/action.yml, .github/workflows/app-ios.yml
Mejora en la configuración SSH para el workflow de app-ios
- Implementación de mejoras en la configuración SSH para el workflow de app-ios
- Optimización del proceso de despliegue
- Actualización de las credenciales de acceso
1. **Configuración SSH**:
- Mejora en la gestión de claves SSH
- Optimización de la configuración de acceso
2. **Workflow de Despliegue**:
- Actualización de los pasos de despliegue
- Implementación de nuevas validaciones de seguridad
- [Jira Ticket INFRA-632](https://taxdown.atlassian.net/browse/INFRA-632)
=> feat: enhance SSH setup in app-ios workflow

.github/workflows/python-service-ruff-uv.yml
Added also the capability of deploying from github to the dev manually so we can also test the deployment process on that environment (for changes, test that the deployment role has enough permissions etc...)
=> feat: parametrize input envs

.github/actions/setup-github-auth/action.yml, .github/workflows/python-library-v2.yml, .github/workflows/python-service-uv-v2.yml
Nuevo workflow para bibliotecas Python que utiliza **ty** como type checker en lugar de mypy. Este workflow evoluciona desde python-library.yml incorporando el type checker de nueva generación de Astral, proporcionando verificación de tipos hasta 20x más rápida manteniendo la misma funcionalidad.
- **Archivo**: `.github/workflows/python-library-v2.yml`
- **Basado en**: `python-library.yml` existente
- **Funcionalidad**: Idéntica al workflow v1 con upgrade de type checker
- **Antes**: `uv run mypy --ignore-missing-imports --scripts-are-modules --package taxdown`
- **Después**: `uv run ty check taxdown`
- **Beneficio**: Verificación de tipos 10x-20x más rápida
- ✅ **Checkout del código** con actions/checkout@v4
- ✅ **Setup Python** con actions/setup-python@v4  
- ✅ **Instalación uv** con …
=> feat: add python-library-v2 workflow with ty type checker and setup-github-auth action
